### ISSUE TITLE
node-sass 3.5.0-beta.1

### ISSUE THREAD

**Issue by TruffleMuffin** [brunch/sass-brunch#103]
Currently I am using 1.9.1 of sass-brunch in a lot of projects. The package.json defines a ^3.0.0 dependency of node-sass, which recently released a beta. The beta is now breaking pretty much all of my projects with the new changes.

Is it possible for you to issue a patch for 1.9.X series of your package to prevent the breaking change from coming in on an npm install.

Thank you

**Comment by paulmillr** [comment]
Please upgrade to 2.0, there should be no breaking changes.
