### ISSUE TITLE
Embedded source maps

### ISSUE THREAD

**Issue by rstacruz** [brunch/sass-brunch#105]
I'd like to use `node-sass` to do embedded source maps. With node-sass, that's:

```js
libsass.render({
  sourceMap: true,
  sourceMapEmbed: true,
  sourceComments: false
})
```

With sass-brunch, though, [that doesn't seem to be possible](https://github.com/brunch/sass-brunch/blob/master/index.js#L138-L149).

Would you consider a provision to make this possible?

**Comment by es128** [comment]
It would be difficult to do properly here when you consider that all the output css will be concatenated. PR welcome if the option can be provided with a straightforward solution.
