### ISSUE TITLE
Initialization error

### ISSUE THREAD

**Issue by diogocampos** [brunch/sass-brunch#107]
The plugin stopped working after I upgraded to Node 6.0. After updating Brunch to 2.7.4, it started throwing the following error:

```
$ LOGGY_STACKS=true brunch build --production
01 May 18:08:05 - error: Initialization error -  Cannot read property 'brunchPluginName' of null 
Type  at loadPackages.filter.arg (/Users/diogo/Code/juros/node_modules/brunch/lib/plugins.js:140:33)
  at Array.filter (native)
  at Object.exports.init (/Users/diogo/Code/juros/node_modules/brunch/lib/plugins.js:139:38)
  at BrunchWatcher.application.loadConfig.then.then.then.cfg (/Users/diogo/Code/juros/node_modules/brunch/lib/watch.js:110:19)
```

The error goes away when I remove `sass-brunch` from my package.json.

This is what I have in my brunch-config.coffee:

```coffee
  plugins:
    sass:
      mode: 'native'
      options: includePaths: ['node_modules']
```

**Comment by did** [comment]
@diogocampos downgrading to node 5.11.0 fixed that issue.

**Comment by jraut** [comment]
I had the same problem with brunch (2.7.7) which was installed globally. As in op, the error apperared for the first time after installing `brunch-sass` and disappeared when bunch-sass was removed from package.json. 

Issue got fixed with `npm uninstall -g brunch && npm install -g brunch`.

**Comment by diogocampos** [comment]
I'm not sure what fixed it, but the error is gone after updating Node, Brunch, and brunch-sass.

**Comment by bellthoven** [comment]
I can confirm the solution. I had the same problem and @jraut's solution worked.

**Comment by AdamT** [comment]
I got this error with node 7.2. However I've found that if I remove `/node_modules` and then run `npm install` again it works fine.

**Comment by DaveSanders** [comment]
This issue cropped up for me today. I [read here](http://slack.elixirhq.com/phoenix/2016-05-11/) to downgrade brunch to 2.6.6.

So I think this is still an open issue? That sass-brunch isn't working with the latest brunch? (^2.7.0)

**Comment by apmiller108** [comment]
Same thing here, @DaveSanders solution worked for me: downgrade brunch to 2.6.6

**Comment by soriyath** [comment]
Nuking `node_modules` and running `nvm install v7` and `npm install` solved the problem for me.
I was using several terminal windows and some didn't switch to node 7, so I had to run `nvm use 7`..
