### ISSUE TITLE
breaking change in node-sass import without a major bump cascading as a breaking change in sass-brunch too

### ISSUE THREAD

**Issue by maxlath** [brunch/sass-brunch#111]
It seems that [node-sass v3.5 was a breaking release](https://github.com/sass/node-sass/issues/1474), thus bumping the version in ff6a7bf was introduced breaking changes here too.

I'm not sure what should be done from there, given that releasing a major version now would still let anyone depending on  `"sass-brunch":"^2.0.0"` get the breaking change. Maybe having a patch reverting to `"node-sass": "~3.4.0"` and then re-reverting to `"node-sass": "~3.7.0"` in a major version?

**Comment by paulmillr** [comment]
yes.
