### ISSUE TITLE
include paths not automatically added?

### ISSUE THREAD

**Issue by COLABORATI** [brunch/sass-brunch#112]
I just want to be sure that I do understand things right - so this code does **not** auto-discover all possible include paths from package.json and bower.json, so I have to manually add all the include paths? Is this right? Or _should_ this tool auto-discover all the paths from installed node modules and/or bower components and something is wrong when a path is not automatically added?
I am trying to use this with foundation and I see that I have to add the include path manually, like mentioned in the README.md - I suspect that this manual step could be avoided, but I am not sure if this feature is already implemented or if this is just wishful thinking. Would you please like to clarify this?

Thank you very much for your attention!

**Comment by paulmillr** [comment]
You need to manually add include paths.
