### ISSUE TITLE
Better error logging on the console

### ISSUE THREAD

**Issue by darren131** [brunch/sass-brunch#123]
I'm wondering if it's possible to get better Sass error reporting on the command line during a `brunch watch` process?

Here's my brunch-config:
```
SRC = 'source'
DIST = 'public'
BROWSERSUPPORT = ['last 2 versions','ie >= 9']

exports.config =
    conventions:
        ignored: [
            /[\\/]_/,
            /(^vendor\/phpunit)[\\/]/
        ]
    paths:
        public: DIST
        watched: [
            SRC
            'vendor'
        ]
    npm:
        enabled: true
        globals:
            $: 'jquery'
            jQuery: 'jquery'
            _: 'underscore'
    files:
        javascripts:
            joinTo:
                'js/main.js': /^source/
                'js/vendor.js': /^node_modules/
            order:
                before: [
                    'node_modules/jquery/dist/jquery.js'
                ]
        stylesheets:
            joinTo:
                'css/main.css': SRC + '/styles/main.scss'
    plugins:
        babel:
            presets: ['es2015']
        sass:
            options:
                debug: 'comments'
                mode: 'native'
                includePaths: [
                    'node_modules/foundation-sites/scss'
                    'node_modules/motion-ui/src'
                    'node_modules/family.scss/source/src'
                ]
        postcss:
            processors: [
                require('autoprefixer')(browsers: BROWSERSUPPORT)
            ]
        fingerprint:
            # Mapping file so your server can serve the right files
            manifest: './public/assets.json'
            publicRootPath: '/'
        overrides:
            production:
                optimize: true
                sourceMaps: false
                plugins:
                    autoReload:
                        enabled: false
                    cleancss:
                        keepSpecialComments: 0
                        removeEmpty: true
                    uglify:
                      mangle: false
                      compress:
                        global_defs:
                          DEBUG: false
```

This is the current error logging I'm getting during a watch:

```
01 Nov 16:10:30 - error: Compiling of source/styles/main.scss failed.  
```

With no further info... I'm using the [7-1 pattern](https://sass-guidelin.es/#the-7-1-pattern) which means I have a ton of Sass files—and I need to know which file is causing the error... 

Have I uncovered a bug or is it _user error_?

Thanks!

**Comment by darren131** [comment]
Any ideas?

**Comment by danniehakan** [comment]
+1 to this. The error that I'm getting myself looks like:

`10 Nov 00:44:27 - error: Compiling of frontend/src/styles/main.sass failed.`

... which basically tells me too little to know what went wrong.

Brunch config:

```javascript
module.exports = {
    paths: {
        public: 'public',
        watched: ['vendor', 'frontend']
    },
    files: {
        stylesheets: {
            joinTo: {
                'css/app.css': /^frontend/
            }
        },
        javascripts: {
            joinTo: {
                'js/app.js': /^frontend/,
                'js/vendor.js': /^node_modules/
            }
        }
    },
    plugins: {
        sass: {
            mode: 'native',
            options: {
                includePaths: ['node_modules/bootstrap-sass/assets/stylesheets'],
                precision: 8
            }
        }
    },
    npm: {
        enabled: true,
        globals: { // bootstrap-sass' JavaScript requires both '$' and 'jQuery' in global scope
            $: 'jquery',
            jQuery: 'jquery'
        }
    },
    modules: {
        wrapper: false
    }
}
```

package.json dependencies:

```javascript
"dependencies": {
    "bootstrap-sass": "3.3.7",
    "jquery": "3.1.1"
  },
  "devDependencies": {
    "brunch": "2.9.1",
    "clean-css-brunch": "2.0.0",
    "css-brunch": "2.6.1",
    "javascript-brunch": "2.0.0",
    "sass-brunch": "2.7.0",
    "uglify-js-brunch": "2.0.1"
  }
```

**Comment by darren131** [comment]
Hi again... any info on this, please?

**Comment by bryanstearns** [comment]
I had this problem too, but switching to master fixed it -- I think @paulmillr's #120 might have done the trick.

**Comment by Slakinov** [comment]
Any more concrete info?
I'm running:

brunch 2.9.1
sass-brunch: 2.7.0

All sass errors just appear as 'error: Compiling of app/scss/style.scss failed.'

Forgive me if I'm being dumb here, but I don't understand how 'switching to master' is applicable since we're just working with whatever NPM throws at us based on our package.json configs...?

**Comment by shvaikalesh** [comment]
Hello @Slakinov, thanks for bringing this up. Will publish new patch version ASAP.

**Comment by shvaikalesh** [comment]
Released as `2.9.0`. Please update & reopen if you continue experiencing the issue.

**Comment by Slakinov** [comment]
Amazing! Thankyou, will try out tomorrow.

**Comment by alancwoo** [comment]
@shvaikalesh I'm on `brunch 2.9.1` and `sass-brunch 2.9.0` and I'm still getting a cryptic `error: Compiling of app/scss/core.scss failed.`

Have I done something wrong?

**Comment by alancwoo** [comment]
@shvaikalesh I'm sorry but I'm still having this problem where the error message completely lacks a description of what the error is, it's making it very hard to debug. Is there any way to remedy this or reopen this issue if it is still occurring for anyone else?

**Comment by fatcop** [comment]
As it happens so am I ... am on version 2.9.1
All I get is:  "error: Compiling of app/app.js failed."

**Comment by wiltzius** [comment]
FWIW if anyone is still experiencing this issue, as I was, it does still manifest in 2.9.1 but if you upgrade to the latest version (currently 2.10.4) with latest brunch (currently 2.10.12) it does display error messages again
