### ISSUE TITLE
Allow adding postcss preprocessors

### ISSUE THREAD

**Issue by kuon** [brunch/sass-brunch#124]
I am currently using https://github.com/brunch/postcss-brunch to apply `autoprefixer` to my css. But it stopped working with `scss` files a while ago.

I noticed that `postcss` is already a dependency of `sass-brunch` and I was wondering if allowing it's configuration wouldn't solve the problem.

In short, can't we add `autoprefixer` (and potentially other) postcss processors support to `sass-brunch`?

**Comment by kgcreative** [comment]
+1

**Comment by kuon** [comment]
I had a look into it, and I think we might go this way (I have not looked at the code yet, but from an architecture point of view, it seems the way to go):

- Make `sass-brunch` not dependent on `postcss`
- Make `sass-brunch` work with https://github.com/css-modules/postcss-modules throught https://github.com/brunch/postcss-brunch with modification to `postcss-brunch` if needed
- Fix https://github.com/brunch/postcss-brunch/issues/31

The idea is to have support for css modules for other css preprocessors (less, stylus...).

If this seems a reasonable approach to @paulmillr and others, I'll try to get PRs to both repo.

ping @rstacruz @lydell @nshafer

**Comment by paulmillr** [comment]
yep

**Comment by kuon** [comment]
https://github.com/brunch/postcss-brunch/pull/33 should also fix this issue, and I made
https://github.com/brunch/sass-brunch/issues/125 to remove unnecessary code

**Comment by omin** [comment]
I would like this as well

**Comment by kuon** [comment]
My proposal to properly fix it https://github.com/brunch/brunch/issues/1565
