### ISSUE TITLE
error when i try to compile a function

### ISSUE THREAD

**Issue by leonardotessaroalves** [brunch/sass-brunch#130]
i dont know if it is a error, but when i try to compile a function  on my scss file i get some error and the process stop. 

@function slick-image-url($url) {
    @if function-exists(image-url) {
        @return image-url($url);
    }
    @else {
        @return url($slick-loader-path + $url);
    }
}

@function slick-font-url($url) {
    @if function-exists(font-url) {
        @return font-url($url);
    }
    @else {
        @return url($slick-font-path + $url);
    }
}

/// ERROR  if i remove this comment ==> /*
.slick-list {
    .slick-loading & {
        background: #fff slick-image-url("ajax-loader.gif") center center no-repeat;
    }
}
*/

**Comment by denysdovhan** [comment]
Hey, @leonardotessaroalves! Could you provide me a repo that reproduces your problem? Please, include your Brunch config, `package.json` and files that cause the problem. I'm going to dive in sources and help you to resolve this issue.
