### ISSUE TITLE
sass-bunch + css-modules + brunch@2.10.0 doesn't wrap modules correctly.

### ISSUE THREAD

**Issue by 32bitkid** [brunch/sass-brunch#133]
It looks like the latest brunch (@2.10.0) doesn't wrap css-modules correctly; generating unusable javascript.

```
$ brunch --version
2.10.0
```

Using an empty skeleton `brunch/dead-simple` and adding `sass-brunch` and the minimal config to enable css-modules:

```
module.exports = {
  files: {
    javascripts: {joinTo: 'app.js'},
    stylesheets: {joinTo: 'app.css'},
    templates: {joinTo: 'app.js'}
  },
  plugins: {
    sass: {
      modules: true
    }
  }
};
```

Then adding a very minimal scss file and compiling:

```
$ echo '.test { background-color: tan; }' > app/foo.scss
$ brunch b
```

Results in a compiled line in app.js with a naked `module.exports`:

```
/* ...snip... */
module.exports = {"test":"_test_e6rji_1"};
/* ...snip... */
```

which, i _think_, should look something more lke:
```
require.register("foo.scss", function(exports, require, module) {
module.exports = {"test":"_test_e6rji_1"};
});
```

**Comment by shvaikalesh** [comment]
Fixed in `2.10.1`.
