### ISSUE TITLE
Cannot import from node_modules without `native: true` (documentation?)

### ISSUE THREAD

**Issue by tomsquest** [brunch/sass-brunch#134]
This issue may be a lack of precise documentation.  
If this is the case, I will write a PR with the relevant part included, or an example.

##### Problem

The only way of importing an external sass file (external = from `node_modules`) is to set `native: true` and with an `@import` from `node_modules` (full path or with an `includePaths`).

##### Example

Here is the one solution (lost a couple of hours to find out) on how to import "normalize-scss" from `node_modules`.

`front/app/app.scss`:

```scss
@import "node_modules/normalize-scss/sass/normalize/import-now";
// "normalize/import-now" comes from normalize-scss documentation
// @import "normalize/import-now" should work with an includePath in brunch-config
```

`brunch-config.js`:
```js
module.exports = {
    plugins: {
        sass: {
            mode: 'native', // does not work without, or with 'ruby'
        }
    },
};
```

##### Versions

```
brunch: 2.9.1
node-sass: 3.8.0
sass-brunch: 2.9.0
```

**Comment by denysdovhan** [comment]
Hi, @tomsquest! Thanks for reporting! Let's see how can I help you. I take this issue and will try to reproduce that behavior. You would help me a lot, if you wrap this out in single github repo.

**Comment by denysdovhan** [comment]
@tomsquest, I've spend an hour trying to reproduce your bug. Here is a repo I created for this reason: [denysdovhan/brunch-sass-134](https://github.com/denysdovhan/brunch-sass-134).

**`brunch-config.js`:**

```js
module.exports = {
  files: {
    stylesheets: {
      joinTo: 'app.css',
    },
  },
  plugins: {
    sass: {
      // mode: 'native', // works as expected without this
      options: {
        // don't you forget to add this ↓ line to your config?
        includePaths: ['node_modules/normalize-scss/sass'],
      },
    },
  },
};
```

With that config it works as expected for me. 

**Versions:**

```
brunch: 2.9.1
normalize-scss": ^6.0.0
sass-brunch: ^2.9.0
node-sass: 3.8.0
```

Please, check your config. Maybe I've missed something important?

**Comment by kgcreative** [comment]
@denysdovhan I also noticed he didn't have includePaths on his plugins / sass / options. That was also going to be my suggestion.

**Comment by tomsquest** [comment]
I am ashamed that I **can't** reproduce this !! (nor in Denys' repo, nor mine ; with `includePaths` or a full path ; with `native` or not). I apologize for the noise.

Closing: not reproducible.

**Comment by denysdovhan** [comment]
@tomsquest ¯\_(ツ)_/¯
