### ISSUE TITLE
Wont install on win 7

### ISSUE THREAD

**Issue by alextsk** [brunch/sass-brunch#151]
Having trouble with installing. My setup:

* **Windonws:** 7 x64
* **Node.js:** 7.2.1
* **npm:** 4.0.2
* **Brunch:** 2.10.9

Trying this:

```
npm install --save-dev sass brunch
```

results in:

```
> Cannot download "https://github.com/sass/node-sass/releases/download/v3.8.0/win32-x64-51_binding.node"
> HTTP error 404 Not Found
```

Then it tries to build nodesass using node-gyp and expectedly fails. The question is: is there a way to install plugin without building?

I also have the Ruby version sass installed (**Sass:** 3.4.23) and wouldn't mind using it instead of node-sass if it is possible.

**Comment by denysdovhan** [comment]
You're right, when i try to `curl` a URL I get this:

```
$ curl https://github.com/sass/node-sass/releases/download/v3.8.0/win32-x64-51_binding.node
Not Found
```

There is no such binding [in `node-sass@3.8.0`](https://github.com/sass/node-sass/releases/tag/v3.8.0). That's strange.

**Comment by denysdovhan** [comment]
If you want to use Ruby version, try this:

```js
module.exports = {
  plugins: {
    sass: {
      mode: 'ruby' // set to 'native' to force libsass
    }
  }
}
```

**Comment by alextsk** [comment]
I thought about using "mode: 'ruby'", but  the problem is plugin is never installed, after build fails no sign of it neither in package json nor in node_modules. i tried to copy and paste it, but it didnt' work out either - phoenix runs npm install automatically and i get the same error.

**Comment by allansson** [comment]
I'm experiencing the same issue on Windows 10 x64.

**Comment by gopalagrawal** [comment]
Noob question here.  What does it mean to "upgrade node-sass to 4.5.3"?  Does it mean I first install node-sass before installing sass-brunch?  Or does it mean I only need to install node-sass?  Confused.
