### ISSUE TITLE
Doesn't compile scss files

### ISSUE THREAD

**Issue by dmitry-saritasa** [brunch/sass-brunch#161]
(crm) ➜  backend git:(develop) ✗ sass -v                         
    Sass 3.5.1 (Bleeding Edge)
    (crm) ➜  backend git:(develop) ✗ dnf list installed G libsass    
    1574:libsass.x86_64                         3.4.5-4.fc26                @updates     

    (crm) ➜  backend git:(develop) ✗ tree  assets
    assets
    ├── css
    │   └── style.css
    ├── fonts
    │   └── README.md
    ├── handlebars
    │   └── readme.md
    ├── js
    │   ├── ajax.js
    │   ├── ajax_mocks.js
    │   ├── application.js
    │   ├── _config.js
    │   ├── events.js
    │   └── readme.md
    ├── mocks
    │   └── readme.md
    ├── revisions
    │   └── readme.md
    └── sass
        ├── app.scss
        ├── base
        │   ├── _base.scss
        │   ├── _buttons.scss
        │   ├── _forms.scss
        │   ├── _grid-settings.scss
        │   ├── _lists.scss
        │   ├── _tables.scss
        │   ├── _typography.scss
        │   └── _variables.scss
        └── vendor
            └── font-awesome
                ├── _animated.scss
                ├── _bordered-pulled.scss
                ├── _core.scss
                ├── _fixed-width.scss
                ├── font-awesome.scss
                ├── _icons.scss
                ├── _larger.scss
                ├── _list.scss
                ├── _mixins.scss
                ├── _path.scss
                ├── _rotated-flipped.scss
                ├── _stacked.scss
                └── _variables.scss

I put a demo class in assets/sass/base.scss

### my assets/sass/app.scss

    // ----------------------------------------
    // ------ set up ------
    // ----------------------------------------
    @import 'base/base';
    
    // ----------------------------------------
    // ------ custom mixins ------
    // ----------------------------------------
    
    // ----------------------------------------
    // ------ partials ------
    // ----------------------------------------
    
    @import 'vendor/font-awesome/font-awesome.scss';

### my assets/base/_base.scss

    // Bitters 1.1.0
    // http://bitters.bourbon.io
    // Copyright 2013-2015 thoughtbot, inc.
    // MIT License
    
    @import "variables";
    @import "buttons";
    @import "forms";
    @import "lists";
    @import "tables";
    @import "typography";
    
    .shit2 {
        color: red;
    }

### my brunch-config.js

    exports.paths = {
      watched: ['assets']
    };
    
    exports.files = {
      javascripts: {
        joinTo: {
          'app.js': /^assets/,
          'vendor.js': /^node_modules/
        }
      },
      stylesheets: {
        joinTo: {
          'vendor.css': /^(?!assets)/,
          'app.css': /^assets/
        }
      }
    };
    
    
    exports.npm = {
      enabled: true,
      globals: {
        jQuery: 'jquery',
        $: 'jquery',
        bootstrap: 'bootstrap'
      },
      styles: {
        bootstrap: ['dist/css/bootstrap.css']
      }
    };
    
    exports.plugins = {
      babel: {presets: ['es2015', 'stage-0']},
      autoReload: {
        enabled: true
      },
      sass: {
        mode: 'native',
        sourceMapEmbed: true
      }
    };

### my package.json

    {
      "name": "django",
      "version": "0.0.0",
      "description": "project dependencies",
      "main": "index.js",
      "directories": {
        "doc": "docs"
      },
      "scripts": {
        "prestart": "./install.sh",
        "start": "LOGGY_STACKS=true brunch watch --server",
        "build": "brunch build --production",
        "poststart": "cowsay -f dragon The Build Is Complete! Do not forget to apply migrations!;",
        "postinstall": ""
      },
      "devDependencies": {
        "eslint-plugin-html": "~3.2.2",
        "auto-reload-brunch": "^2.7.1",
        "babel-brunch": "~6.1",
        "babel-preset-latest": "^6",
        "babel-preset-stage-0": "^6.24.1",
        "babel-preset-es2015": "~6.24.1",
        "brunch": "^2",
        "clean-css-brunch": "^2",
        "css-brunch": "^2.10.0",
        "sass-brunch": "^2.10",
        "javascript-brunch": "^2.10.0",
        "uglify-js-brunch": "^2",
        "jade-brunch": "^2.8",
        "handlebars-brunch": "^2.10"
      },
      "dependencies": {
        "bootstrap": "^3.3.7",
        "jquery": "^3.2.1",
        "lodash": "^4.17.4",
        "alertify.js": "^1.0.12",
        "bootstrap-table": "~1.11.2",
        "bootstrap": "~3.3.7",
        "js-cookie": "~2.1.4",
        "underscore": "~1.8.3",
        "string": "^3.3.3",
        "jquery-validation": "^1.17.0",
        "jquerypp": "^2.0.2",
        "jquery-mockjax": "^2.2.2",
        "handlebars": "^4.0.10"
      },
      "author": "saritasa.com",
      "license": "BSD",
      "repository": {
        "type": "git",
        "url": "git://github.com/username/repository.git"
      }
    }

# Output of build process

    (crm) ➜  backend git:(develop) ✗ brunch build -d
      brunch:config Trying to load brunch-config +0ms
      brunch:plugins Loaded plugins: auto-reload-brunch, babel-brunch, sass-brunch, jade-brunch, handlebars-brunch +2s
      brunch:list Reading node_modules/jade/runtime.js +14ms
      brunch:list Reading node_modules/handlebars-brunch/dist/handlebars.runtime.js +2ms
      brunch:list Reading node_modules/handlebars-brunch/ns.js +1ms
      brunch:watch add package.json +31ms
      brunch:watch add brunch-config.js +1ms
      brunch:watch add /home/dmitry/Projects/crm/backend/node_modules/bootstrap/dist/css/bootstrap.css +0ms
      brunch:list Reading node_modules/bootstrap/dist/css/bootstrap.css +0ms
      brunch:watch add node_modules/jquery/dist/jquery.js +1ms
      brunch:list Reading node_modules/jquery/dist/jquery.js +0ms
      brunch:watch add node_modules/bootstrap/dist/js/npm.js +0ms
      brunch:list Reading node_modules/bootstrap/dist/js/npm.js +0ms
      brunch:file Init file node_modules/jade/runtime.js +5ms
      brunch:pipeline Compiling node_modules/jade/runtime.js @ auto-reload-brunch +5ms
      brunch:pipeline Compiling node_modules/jade/runtime.js @ babel-brunch +2ms
      brunch:list Compiled node_modules/jade/runtime.js +694ms
      brunch:file Init file node_modules/handlebars-brunch/dist/handlebars.runtime.js +1ms
      brunch:pipeline Compiling node_modules/handlebars-brunch/dist/handlebars.runtime.js @ auto-reload-brunch +0ms
      brunch:pipeline Compiling node_modules/handlebars-brunch/dist/handlebars.runtime.js @ babel-brunch +1ms
      brunch:list Compiled node_modules/handlebars-brunch/dist/handlebars.runtime.js +807ms
      brunch:file Init file node_modules/handlebars-brunch/ns.js +1ms
      brunch:pipeline Compiling node_modules/handlebars-brunch/ns.js @ auto-reload-brunch +0ms
      brunch:pipeline Compiling node_modules/handlebars-brunch/ns.js @ babel-brunch +1ms
      brunch:list Compiled node_modules/handlebars-brunch/ns.js +22ms
      brunch:file Init file node_modules/bootstrap/dist/js/npm.js +0ms
      brunch:file Init file node_modules/bootstrap/dist/css/bootstrap.css +3ms
      brunch:list Compiled node_modules/bootstrap/dist/css/bootstrap.css +23ms
      brunch:file Init file node_modules/jquery/dist/jquery.js +0ms
      brunch:list Reading node_modules/process/browser.js +278ms
      brunch:list Compiled node_modules/jquery/dist/jquery.js +45ms
      brunch:watch add assets/app.css +13ms
      brunch:list Reading assets/app.css +0ms
      brunch:watch add assets/app.js +1ms
      brunch:list Reading assets/app.js +0ms
      brunch:file Init file node_modules/process/browser.js +1ms
      brunch:asset Init asset assets/app.css +3ms
      brunch:list Compiled assets/app.css +3ms
      brunch:asset Init asset assets/app.js +0ms
      brunch:list Compiled assets/app.js +3ms
      brunch:list Reading node_modules/bootstrap/js/transition.js +62ms
      brunch:list Reading node_modules/bootstrap/js/alert.js +0ms
      brunch:list Reading node_modules/bootstrap/js/button.js +0ms
      brunch:list Reading node_modules/bootstrap/js/carousel.js +0ms
      brunch:list Reading node_modules/bootstrap/js/collapse.js +1ms
      brunch:list Reading node_modules/bootstrap/js/dropdown.js +0ms
      brunch:list Reading node_modules/bootstrap/js/modal.js +0ms
      brunch:list Reading node_modules/bootstrap/js/tooltip.js +0ms
      brunch:list Reading node_modules/bootstrap/js/popover.js +0ms
      brunch:list Reading node_modules/bootstrap/js/scrollspy.js +0ms
      brunch:list Reading node_modules/bootstrap/js/tab.js +0ms
      brunch:list Reading node_modules/bootstrap/js/affix.js +1ms
      brunch:list Compiled node_modules/bootstrap/dist/js/npm.js +0ms
      brunch:list Compiled node_modules/process/browser.js +10ms
      brunch:file Init file node_modules/bootstrap/js/transition.js +1ms
      brunch:list Compiled node_modules/bootstrap/js/transition.js +16ms
      brunch:file Init file node_modules/bootstrap/js/alert.js +0ms
      brunch:list Compiled node_modules/bootstrap/js/alert.js +17ms
      brunch:file Init file node_modules/bootstrap/js/button.js +0ms
      brunch:list Compiled node_modules/bootstrap/js/button.js +17ms
      brunch:file Init file node_modules/bootstrap/js/carousel.js +0ms
      brunch:list Compiled node_modules/bootstrap/js/carousel.js +37ms
      brunch:file Init file node_modules/bootstrap/js/collapse.js +0ms
      brunch:list Compiled node_modules/bootstrap/js/collapse.js +9ms
      brunch:file Init file node_modules/bootstrap/js/dropdown.js +0ms
      brunch:list Compiled node_modules/bootstrap/js/dropdown.js +27ms
      brunch:file Init file node_modules/bootstrap/js/modal.js +0ms
      brunch:list Compiled node_modules/bootstrap/js/modal.js +17ms
      brunch:file Init file node_modules/bootstrap/js/tooltip.js +0ms
      brunch:list Compiled node_modules/bootstrap/js/tooltip.js +12ms
      brunch:file Init file node_modules/bootstrap/js/popover.js +0ms
      brunch:list Compiled node_modules/bootstrap/js/popover.js +5ms
      brunch:file Init file node_modules/bootstrap/js/scrollspy.js +0ms
      brunch:list Compiled node_modules/bootstrap/js/scrollspy.js +6ms
      brunch:file Init file node_modules/bootstrap/js/tab.js +0ms
      brunch:list Compiled node_modules/bootstrap/js/tab.js +7ms
      brunch:file Init file node_modules/bootstrap/js/affix.js +0ms
      brunch:list Compiled node_modules/bootstrap/js/affix.js +7ms
      brunch:watch add assets/css/client.css +8ms
      brunch:list Reading assets/css/client.css +0ms
      brunch:watch add assets/css/client.css.map +1ms
      brunch:list Reading assets/css/client.css.map +0ms
      brunch:watch add assets/css/style.css +0ms
      brunch:list Reading assets/css/style.css +0ms
      brunch:watch add assets/fonts/README.md +1ms
      brunch:list Reading assets/fonts/README.md +0ms
      brunch:watch add assets/handlebars/readme.md +1ms
      brunch:list Reading assets/handlebars/readme.md +0ms
      brunch:watch add assets/js/_config.js +0ms
      brunch:list Reading assets/js/_config.js +0ms
      brunch:watch add assets/js/ajax_mocks.js +1ms
      brunch:list Reading assets/js/ajax_mocks.js +0ms
      brunch:watch add assets/js/ajax.js +0ms
      brunch:list Reading assets/js/ajax.js +0ms
      brunch:watch add assets/js/application.js +0ms
      brunch:list Reading assets/js/application.js +0ms
      brunch:watch add assets/js/events.js +1ms
      brunch:list Reading assets/js/events.js +0ms
      brunch:watch add assets/js/readme.md +0ms
      brunch:list Reading assets/js/readme.md +0ms
      brunch:watch add assets/mocks/readme.md +1ms
      brunch:list Reading assets/mocks/readme.md +0ms
      brunch:watch add assets/revisions/readme.md +0ms
      brunch:list Reading assets/revisions/readme.md +1ms
      brunch:watch add assets/sass/app.scss +1ms
      brunch:list Reading assets/sass/app.scss +0ms
      brunch:asset Init asset assets/css/client.css +1ms
      brunch:list Compiled assets/css/client.css +1ms
      brunch:asset Init asset assets/css/client.css.map +0ms
      brunch:list Compiled assets/css/client.css.map +1ms
      brunch:asset Init asset assets/css/style.css +0ms
      brunch:list Compiled assets/css/style.css +0ms
      brunch:asset Init asset assets/fonts/README.md +0ms
      brunch:list Compiled assets/fonts/README.md +1ms
      brunch:asset Init asset assets/handlebars/readme.md +0ms
      brunch:list Compiled assets/handlebars/readme.md +1ms
      brunch:asset Init asset assets/js/ajax_mocks.js +0ms
      brunch:list Compiled assets/js/ajax_mocks.js +1ms
      brunch:asset Init asset assets/js/ajax.js +0ms
      brunch:list Compiled assets/js/ajax.js +1ms
      brunch:asset Init asset assets/js/application.js +1ms
      brunch:list Compiled assets/js/application.js +0ms
      brunch:asset Init asset assets/js/events.js +1ms
      brunch:list Compiled assets/js/events.js +1ms
      brunch:asset Init asset assets/mocks/readme.md +0ms
      brunch:list Compiled assets/mocks/readme.md +0ms
      brunch:asset Init asset assets/revisions/readme.md +1ms
      brunch:list Compiled assets/revisions/readme.md +1ms
      brunch:asset Init asset assets/js/readme.md +0ms
      brunch:list Compiled assets/js/readme.md +1ms
      brunch:asset Init asset assets/sass/app.scss +1ms
      brunch:list Compiled assets/sass/app.scss +0ms
      brunch:watch add assets/sass/base/_base.scss +10ms
      brunch:list Reading assets/sass/base/_base.scss +0ms
      brunch:watch add assets/sass/base/_buttons.scss +1ms
      brunch:list Reading assets/sass/base/_buttons.scss +0ms
      brunch:watch add assets/sass/base/_forms.scss +0ms
      brunch:list Reading assets/sass/base/_forms.scss +0ms
      brunch:watch add assets/sass/base/_grid-settings.scss +1ms
      brunch:list Reading assets/sass/base/_grid-settings.scss +0ms
      brunch:watch add assets/sass/base/_lists.scss +0ms
      brunch:list Reading assets/sass/base/_lists.scss +0ms
      brunch:watch add assets/sass/base/_tables.scss +1ms
      brunch:list Reading assets/sass/base/_tables.scss +0ms
      brunch:watch add assets/sass/base/_typography.scss +0ms
      brunch:list Reading assets/sass/base/_typography.scss +0ms
      brunch:watch add assets/sass/base/_variables.scss +1ms
      brunch:list Reading assets/sass/base/_variables.scss +0ms
      brunch:watch add assets/sass/vendor/font-awesome/_animated.scss +8ms
      brunch:list Reading assets/sass/vendor/font-awesome/_animated.scss +0ms
      brunch:watch add assets/sass/vendor/font-awesome/_bordered-pulled.scss +1ms
      brunch:list Reading assets/sass/vendor/font-awesome/_bordered-pulled.scss +0ms
      brunch:watch add assets/sass/vendor/font-awesome/_core.scss +0ms
      brunch:list Reading assets/sass/vendor/font-awesome/_core.scss +0ms
      brunch:watch add assets/sass/vendor/font-awesome/_fixed-width.scss +1ms
      brunch:list Reading assets/sass/vendor/font-awesome/_fixed-width.scss +0ms
      brunch:watch add assets/sass/vendor/font-awesome/_icons.scss +0ms
      brunch:list Reading assets/sass/vendor/font-awesome/_icons.scss +0ms
      brunch:watch add assets/sass/vendor/font-awesome/_larger.scss +0ms
      brunch:list Reading assets/sass/vendor/font-awesome/_larger.scss +0ms
      brunch:watch add assets/sass/vendor/font-awesome/_list.scss +0ms
      brunch:list Reading assets/sass/vendor/font-awesome/_list.scss +0ms
      brunch:watch add assets/sass/vendor/font-awesome/_mixins.scss +2ms
      brunch:list Reading assets/sass/vendor/font-awesome/_mixins.scss +0ms
      brunch:watch add assets/sass/vendor/font-awesome/_path.scss +0ms
      brunch:list Reading assets/sass/vendor/font-awesome/_path.scss +0ms
      brunch:watch add assets/sass/vendor/font-awesome/_rotated-flipped.scss +0ms
      brunch:list Reading assets/sass/vendor/font-awesome/_rotated-flipped.scss +0ms
      brunch:watch add assets/sass/vendor/font-awesome/_stacked.scss +1ms
      brunch:list Reading assets/sass/vendor/font-awesome/_stacked.scss +0ms
      brunch:watch add assets/sass/vendor/font-awesome/_variables.scss +0ms
      brunch:list Reading assets/sass/vendor/font-awesome/_variables.scss +0ms
      brunch:watch add assets/sass/vendor/font-awesome/font-awesome.scss +0ms
      brunch:list Reading assets/sass/vendor/font-awesome/font-awesome.scss +0ms
      brunch:asset Init asset assets/sass/vendor/font-awesome/font-awesome.scss +4ms
      brunch:list Compiled assets/sass/vendor/font-awesome/font-awesome.scss +1ms
      brunch:write Writing 2/2 files +72ms
      brunch:generate Concatenating [node_modules/bootstrap/dist/js/npm.js, node_modules/bootstrap/js/affix.js, node_modules/bootstrap/js/alert.js, node_modules/bootstrap/js/button.js, node_modules/bootstrap/js/carousel.js, node_modules/bootstrap/js/collapse.js, node_modules/bootstrap/js/dropdown.js, node_modules/bootstrap/js/modal.js, node_modules/bootstrap/js/popover.js, node_modules/bootstrap/js/scrollspy.js, node_modules/bootstrap/js/tab.js, node_modules/bootstrap/js/tooltip.js, node_modules/bootstrap/js/transition.js, node_modules/handlebars-brunch/dist/handlebars.runtime.js, node_modules/handlebars-brunch/ns.js, node_modules/jade/runtime.js, node_modules/jquery/dist/jquery.js, node_modules/process/browser.js] => public/vendor.js +8ms
      brunch:generate Concatenating [node_modules/bootstrap/dist/css/bootstrap.css] => public/vendor.css +133ms
      brunch:generate Writing public/vendor.js +46ms
      brunch:generate Writing public/vendor.js.map +13ms
      brunch:generate Writing public/vendor.css +1ms
      brunch:generate Writing public/vendor.css.map +6ms
      brunch:write Writing 16/16 assets, removing 0 +16ms
      brunch:generate Writing public/app.css +1ms
      brunch:generate Writing public/app.js +0ms
      brunch:generate Writing public/css/client.css +0ms
      brunch:generate Writing public/css/client.css.map +5ms
      brunch:generate Writing public/css/style.css +1ms
      brunch:generate Writing public/fonts/README.md +0ms
      brunch:generate Writing public/handlebars/readme.md +1ms
      brunch:generate Writing public/js/ajax_mocks.js +0ms
      brunch:generate Writing public/js/ajax.js +0ms
      brunch:generate Writing public/js/application.js +1ms
      brunch:generate Writing public/js/events.js +0ms
      brunch:generate Writing public/mocks/readme.md +0ms
      brunch:generate Writing public/revisions/readme.md +1ms
      brunch:generate Writing public/js/readme.md +0ms
      brunch:generate Writing public/sass/app.scss +0ms
      brunch:generate Writing public/sass/vendor/font-awesome/font-awesome.scss +1ms
    13:53:06 - info: compiled 19 files into 2 files, copied 16 in 5.5 sec

---

The problem is that I don't see **'.shit2'** class in the final public/app.css file. If I run local 'sass' using cli against assets/sass/app.scss - I get a compiled css with such **.shit2** class included. 
Also I have **libsass** installed as well

**What am I doing wrong?**

after build I get the following files in the public folder

```
(crm) ➜  backend git:(develop) ✗ brunch build   
14:11:37 - info: compiling
14:11:38 - info: compiled 19 files into 2 files, copied 11 in 5.1 sec
(crm) ➜  backend git:(develop) ✗ tree public
public
├── css
│   └── style.css
├── fonts
│   └── README.md
├── handlebars
│   └── readme.md
├── js
│   ├── ajax.js
│   ├── ajax_mocks.js
│   ├── application.js
│   ├── events.js
│   └── readme.md
├── mocks
│   └── readme.md
├── sass
│   ├── app.scss
│   └── vendor
│       └── font-awesome
│           └── font-awesome.scss
├── vendor.css
├── vendor.css.map
├── vendor.js
└── vendor.js.map

```

**Comment by voiddragon** [comment]
Had the same issue, brunch directly copies all copies of any folders named "assets" without processing

https://github.com/brunch/brunch-guide/blob/master/content/en/chapter03-conventions-and-defaults.md#folders

**Comment by Custodia** [comment]
I have the same issue but my scss files are not in a folder called assets

**Comment by Virrum** [comment]
I have the same issue. The debug stack says that the css file is copmiled, but it silently stops without any feedback warning or errors. 
When I remove `@import "../../../node_modules/bootstrap-sass/assets/stylesheets/_bootstrap";
` from my `app/styles/app.scss`file, everything works.

Any ideas?

**Comment by Custodia** [comment]
I was able to resolve my issues by doing `git clean -fdx` and rebuilding everything from scratch. Not sure what the actual root cause was.
