### ISSUE TITLE
Failed postinstall script on Linux-x64-57 ( node-sass dependency needs to be updated)

### ISSUE THREAD

**Issue by JeuelyFish** [brunch/sass-brunch#168]
I have `"sass-brunch": "^2.10.4",` in my package.json and when I `npm install` my packages I'm getting a 
```
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@3.8.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!  
npm ERR! Failed at the node-sass@3.8.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
````

When looking at the logs above that error message I see a 

```
> node-sass@3.8.0 install /home/...
> node scripts/install.js

Cannot download "https://github.com/sass/node-sass/releases/download/v3.8.0/linux-x64-57_binding.node":

HTTP error 404 Not Found
```
When looking at the[ v3.8.0 release of node-sass](https://github.com/sass/node-sass/releases/tag/v3.8.0), there doesnt seem to be a asset file for my environment Linux-x64-57.
This is not the case, however, for more recently [released versions of node-sass.](https://github.com/sass/node-sass/releases) Namely, the most recent version v4.7.2.

Are there any plans to update the node-sass dependency?

**Comment by ctomp** [comment]
I'm having the same issue, except it's looking for win32-x64-57:
```
> node scripts/install.js

Cannot download "https://github.com/sass/node-sass/releases/download/v3.8.0/win32-x64-57_binding.node":

HTTP error 404 Not Found
```
For the time being I'm using the code directly from the master branch but it would be nice to have a new stable release.

**Comment by entwanderer** [comment]
Same problem here when trying to install sass-brunch with npm.

```> node-sass@3.8.0 install C:\myproject
> node scripts/install.js

Cannot download "https://github.com/sass/node-sass/releases/download/v3.8.0/win32-x64-57_binding.node":

HTTP error 404 Not Found
```

sass-brunch itself has 4.x as dependency, but some of the other dependencies may have 3.x of node-sass?

**Comment by johnrobertporter** [comment]
I have the same issue on Mac OS High Sierra.

**Comment by samuelludwig** [comment]
Has anyone figured out any fixes to this? I'm having a very similar problem but on windows;

```
> node scripts/install.js

Cannot download "https://github.com/sass/node-sass/releases/download/v3.8.0/win32-x64-67_binding.node":

HTTP error 404 Not Found
```

**Comment by Biquette** [comment]
Hello,

I had this problem a while ago, so I give you a workaround.

On my side, the download is not possible for proxy reasons.



1) Retrieve node-sass bindings binary

The version number and file name are meant to change accordingly to your NPM install version and node-sass version.

Here are the displayed data in your console :

`Downloading binary from https://github.com/sass/node-sass/releases/download/v4.11.0/win32-x64-64_binding.node`

What this line is telling you is that you are trying to call this url :
https://github.com/sass/node-sass/releases/download/v4.11.0/win32-x64-64_binding.node

The formalism for the URL is : https://github.com/sass/node-sass/releases/download/\<version number linked with your NPM version>/\<binding version linked with your OS and the node-sass you are working with>_binding.node

- Binary is available at given URL by console ? download it and go to step 2

- Binary is not available (404 error) :

Maybe Github is not referencing the vx.xx.xx version required by your install. In this case, go to this URL : 
https://github.com/sass/node-sass/releases/
And select last release in the list (ex : v4.12.0). You should find the binary you are looking for and required by your installation.
Download it and go to step 2.

2) Paste the dowloaded file in your <<C:\Users\<YOUR ACCOUNT NAME>\AppData\Roaming\npm-cache\node-sass\<Version to insert>\>> folder
The version is the version of your npm installation. In my example it was 4.11.0 (https://github.com/sass/node-sass/releases/download/**v4.11.0**/win32-x64-64_binding.node)
Do not put the little v.

3) Relaunch your npm install command line at your project location.
This should work locally.

Same process to do on you build pipeline.

Hope it helped.
