### ISSUE TITLE
Issue with watching underscore files with 2.10.7

### ISSUE THREAD

**Issue by mjankowski** [brunch/sass-brunch#178]
I have an `app.scss` which uses `@import` to pull in a bunch of files named like `_partial.scss`.

Under 2.10.5, while running `brunch watch`, changes to the partials trigger a rebuild of the main `app.scss`. After an upgrade to 2.10.7, changing the partials is noticed by brunch but does not trigger a rebuild.

I assume this is related either to the progeny version bump, or the way sass-brunch interfaces with progeny.

**Comment by dlepaux** [comment]
@mjankowski https://www.npmjs.com/package/sass-brunch/v/2.10.8
Fix your issue
