### ISSUE TITLE
scss modules / partial (_example.scss) not recompiled during brunch watch process

### ISSUE THREAD

**Issue by plalance** [brunch/sass-brunch#179]
### Description

scss modules imported in main.scss are not recompiled correclty during brunch watch process.

Files :
components/_example.scss
main.scss

In main.scss :
@import "./components/example";

### Expected behavior

When i edit _something.scss (imported in main.scss), brunch watch should recompile this file and refresh browser's style with new _something.scss modifications.

### Actual behavior

If i edit a partial (_something.scss) brunch watch only writes :  compiled in XX ms.
Instead of recompiling main.scss : compiled main.scss into app.css in XX ms.

!!! I had to fix sass-brunch version to "2.10.5" to make this work like before...
It fix the issue for the moment but the actual version 2.10.7 is buggy with partials compilation...

### Here is my package.json
{
  "name": "base",
  "version": "1.0.0",
  "description": "base ====",
  "main": "web/app.js",
  "directories": {
    "test": "tests"
  },
  "dependencies": {
    "axios": "^0.16.2",
    "element-ui": "^2.4.7",
    "jquery": "^3.3.1",
    "jquery.2": "^1.0.0",
    "json-brunch": "^1.5.4",
    "lodash": "^4.17.4",
    "moment": "^2.22.2",
    "sass-brunch": "2.10.5",
    "vue": "^2.4.2",
    "vue-axios": "^2.0.2",
    "vue-i18n": "^8.1.0",
    "vue-loader": "^13.0.4",
    "vue-lodash": "^2.0.0",
    "vue-moment": "^4.0.0",
    "vue-router": "^2.7.0",
    "vuex": "^3.0.1"
  },
  "devDependencies": {
    "auto-reload-brunch": "^2",
    "babel-brunch": "^6.0.6",
    "babel-plugin-transform-runtime": "^6.22.0",
    "babel-polyfill": "^6.26.0",
    "babel-preset-env": "^1.6.1",
    "babel-preset-es2015": "^6.22.0",
    "babel-preset-es2016": "^6.22.0",
    "babel-preset-stage-3": "^6.22.0",
    "brunch": "^2",
    "clean-css-brunch": "^2",
    "copycat-brunch": "^1.1.0",
    "es6-promise": "^4.2.4",
    "uglify-js-brunch": "^2",
    "vue-template-compiler": "^2.3.4",
    "vue2-brunch": "^1.0.0"
  },
  "scripts": {
    "start": "brunch watch --server",
    "build": "brunch build",
    "debug": "brunch build --debug",
    "compile": "brunch build -p"
  }
}

#### Here is my brunch-config.js file

'use strict';

exports.config = {
    paths: {
        'public': 'web',
        'watched': ['build', 'web/traductions']
    },
    conventions: {
        'assets': /^build\/assets/
    },
    files: {
        javascripts: {
            joinTo: {
                'js/app.js': /^build/,
                'js/vendor.js': /^(?!build)/
            }
        },
        stylesheets: {
            joinTo: {
                'css/app.css': /^build\/scss/
            }
        },
        templates: {
            joinTo: 'js/app.js'
        }
    },
    modules: {
        autoRequire: {
            'app.js': ['build/main.js']
        },
        sass:{
            mode: 'native'
        }
    },
    npm: {
        enabled: true
    },
    plugins: {
        babel: {},
        sass: {
            mode: 'native'
        },
        copycat:{
            "images": ["./build/images"],
            // "js": ['./node_modules/jquery/dist/jquery.slim.js'],
            verbose : false, //shows each file that is copied to the destination directory
            onlyChanged: true //only copy a file if it's modified time has changed (only effective when using brunch watch)
        },
        uglify: {
            mangle: false,
            compress: {
                global_defs: {
                    DEBUG: true
                }
            }
        }
    }
};

**Comment by mdarby** [comment]
As mentioned by @plalance, this fix has Live Reload working again for me:
In `assets/package.json` update the `sass-brunch` line to: `"sass-brunch": "2.10.5"`

**Comment by dlepaux** [comment]
@plalance The new release fix your issue as with @jualoppaz
https://www.npmjs.com/package/sass-brunch/v/2.10.8

**Comment by augnustin** [comment]
2.10.8 was the minimum version required to fix the bug to me.
