### ISSUE TITLE
please release updated npm package

### ISSUE THREAD

**Issue by lguminski** [brunch/sass-brunch#192]
the latest npm package is from January 2019 (2.10.8) and fails to install due to a problem with an outdated dependency (node-gyp).

but when installing from latest commit (December 2019) with
 
    yarn add https://github.com/brunch/sass-brunch\#e31bfe4eb559796a6b0a6be906377ff785785dc4  --dev

it installs properly.

So please release a new npm package containing the commits.

**Comment by paulmillr** [comment]
Released

cc @lguminski @sjoonk @reubano

**Comment by lguminski** [comment]
thank you @paulmillr !
