### ISSUE TITLE
Source map generation failure on Windows

### ISSUE THREAD

**Issue by euantorano** [brunch/sass-brunch#194]
`sass-brunch` v3.0.0 fails to run on Windows, with an error relating to source map generation:

```
> brunch build --production

13:18:38 - info: compiling
13:18:38 - error: Source map generation failed for '..\..\..\..\..\C:\_Dev\projects\apps\Foo\trunk\frontend\styles\main.scss':  ENOENT: no such file or directory, open 'C:\C:\_Dev\projects\apps\Foo\trunk\frontend\styles\main.scss'
Stack trace was suppressed. Run with `LOGGY_STACKS=1` to see the trace.
13:18:38 - error: Source map generation failed for '..\..\..\..\..\C:\_Dev\projects\apps\Foo\trunk\node_modules\bulma\bulma.sass':  ENOENT: no such file or directory, open 'C:\C:\_Dev\projects\apps\Foo\trunk\node_modules\bulma\bulma.sass'
Stack trace was suppressed. Run with `LOGGY_STACKS=1` to see the trace.
...
```

This is repeated for every single SCSS file.

It looks like the WIndows CI also failed for commit 83dc077.

**Comment by paulmillr** [comment]
yeah

**Comment by brodysmith1** [comment]
Would you recommend any temporary workarounds to this? I love the sass/brunch combo, but I'm a noob and can't figure this out.

**Comment by jkruse** [comment]
Any workaround for this, other than downgrading? It seems to try to open "C:\C:\..." which clearly isn't a valid path.

**Comment by gcatto** [comment]
Any identified solutions or workarounds for this?

**Comment by Darkthunder119** [comment]
Also experiencing this problem on Windows. Was wondering if i broke something but bug it is!

Gonna play around with downgrading sass-brunch

**Comment by xxvii** [comment]
Still no solution or workaround to this? 
It's almost one year...it's impossibile to use sass-brunch on windows...

**Comment by euantorano** [comment]
No solution as far as I'm aware. We actually ended up switching back to Webpack as we were use it for other projects.

**Comment by jkruse** [comment]
Pull request #197 fixes this issue with just one character changed. Tests still fail on Windows though (but not because of this).

**Comment by paulmillr** [comment]
Thank you

**Comment by jkruse** [comment]
No, thank you! Happy to contribute.

**Comment by gcatto** [comment]
Would it be possible to get a release (3.0.1) with this fix (and whatever else)?
