### ISSUE TITLE
Source map generation error when deploying to Heroku

### ISSUE THREAD

**Issue by gcatto** [brunch/sass-brunch#201]
I have been trying to add sass-brunch support to my app, which I deploy to Heroku. When I do so, I get a bunch of errors like the following:

`error: Source map generation failed for 'tmp/build_bbbbbbbb/app/views/styles/foo.scss':  ENOENT: no such file or directory, open '/tmp/build_bbbbbbbb/tmp/build_bbbbbbbb/app/views/styles/foo.scss'`

I have tried both `3.0.0` and `brunch/sass-brunch#master`, both of which work locally for me (but I am on Windows), and both of which fail on Heroku. I am using node `14.17.0` and npm `7.14.0`. Unsure if it matters, but my Heroku setup uses `NODE_ENV=staging`.

Any ideas would be appreciated. Thanks!

**Comment by gcatto** [comment]
Found this and tried it, but did not help: https://github.com/brunch/brunch/issues/1558

**Comment by gcatto** [comment]
Got a chance to get back to this, and it seems to be caused by this change: https://github.com/brunch/sass-brunch/commit/e32d3fc3fb12251e857c4fb687bc4dbf4e5aa5eb

If I use `3.0.0`, then it works fine on Heroku, but not locally (I am on Windows). If I use `brunch/sass-brunch#master` then it breaks on Heroku, but works locally.

**Comment by gcatto** [comment]
I was able to make a workaround fix for myself for this by change this line: https://github.com/brunch/sass-brunch/blob/master/index.js#L124

To be:
```
src.replace(process.platform === 'win32' ? 'file:///' : 'file://', '')
```

**Comment by jiixing** [comment]
Can confirm gcatto patch fix the same issue I encountered in windows

**Comment by jkruse** [comment]
This is now fixed on master
