### ISSUE TITLE
Readme refers to unused Sass implementations

### ISSUE THREAD

**Issue by PixievoltNo1** [brunch/sass-brunch#205]
Reading this project's documentation and seeing references to "gems" and "libsass" had me concerned this package is horribly under-maintained, until I checked the package.json and found out this project does in fact use Dart Sass. The readme should be cleaned up to only include info relevant to the current Dart Sass implementation.

I'm willing to take on this work myself if you need me to.

**Comment by paulmillr** [comment]
Hey,

Yes, please.
