### ISSUE TITLE
eliminate ruby dependency

### ISSUE THREAD

**Issue by es128** [brunch/sass-brunch#23]
Opening this issue just to gage interest.

It would be possible to create an alternate version of this plugin using [node-sass](https://github.com/andrew/node-sass)/[libsass](https://github.com/hcatlin/libsass), thereby eliminating the need to install ruby and the sass gem in order to compile sass/scss with brunch.

A node-sass version would resolve problems with compilation slowness and things like using brunch on heroku as described in https://github.com/brunch/sass-brunch/issues/5#issuecomment-15482165.

However, the massive drawback is that it would _not_ support compass at this point (see https://github.com/hcatlin/libsass/issues/82). It apparently would support bourbon.

Are there enough people using sass without compass (with brunch) to make this worthwhile?

Is it perhaps worth trying to roll the additional node-sass dependency into this same plugin and using it automatically when compass is not being utilized?

Please comment with any thoughts or +1s.

**Comment by virtualfunction** [comment]
Can I ask what the sassRe is doing here. It seems that .sass files are compiling with ruby. I'm using bourbon with .sass files but have no need for Ruby. I'm hacking round it with a cheeky `SassCompiler::_rubyCompile = SassCompiler::_nativeCompile` line in my brunch-config.coffee file

**Comment by pikeas** [comment]
Same problem here, why does sass-brunch send `.sass` files to Ruby's sass gem instead of to node-sass?

@virtualfunction's hack worked for me with a slight modification:

    SassCompiler = require('sass-brunch')
    SassCompiler.prototype._rubyCompile = SassCompiler.prototype._nativeCompile
