### ISSUE TITLE
Support sass syntax with libsass

### ISSUE THREAD

**Issue by alp82** [brunch/sass-brunch#77]
I have .sass files with indented syntax. sass-brunch fails to build them properly because it thinks that they are scss files:

    error: Compiling of 'foo.sass' failed. invalid top-level expression

Is there a switch or option to fix this?

**Comment by paulmillr** [comment]
The plugin should automatically detect the correct syntax. Something is wrong. The tests are passing though. Would you mind to share the file with us?

**Comment by alp82** [comment]
I forgot to mention that i use the native libsass library, the ruby version is not installed.

I created a minimal test for that. My file (throws the above error):

    div
       color: red

This works though:

    div {
      color: red;
    }

**Comment by paulmillr** [comment]
libsass doesn't support `.sass`.

**Comment by paulmillr** [comment]
Just checked the source code. It seems it actually does support it with the `sass2scss` addition. We'll need to take a look.

**Comment by alp82** [comment]
gulp-sass uses libsass too and has no problems with `.sass` syntax

**Comment by tamlyn** [comment]
I think node-sass just needs `indentedSyntax: true` to work https://github.com/sass/node-sass#indentedsyntax

**Comment by coulix** [comment]
I also get this issue with 1.8.10. Even with 

        sass: {
            mode: "native",
            options: {
                indentedSyntax: true  // or "true"
            }
        }


15 Aug 07:06:48 - error: Compiling of 'ondemand_web/static/css/base.sass' failed. invalid top-level expression


    #foobar
        opacity: 0
        position: fixed
        bottom: -150px

**Comment by hayesgm** [comment]
Fixed this by bumping to `node-sass` 3.0, which currently isn't supported on the mainline of sass-brunch. You can fork this and bump the version of `node-sass`, or just add the following version which is a current pull request to this library (see #84).

**package.json**
```json
...
"dependencies": {
  "node-sass": "^3.3.2",
  "sass-brunch": "git+ssh://git@github.com:leadtrader/sass-brunch.git",
  ...
}

```

**Comment by realistschuckle** [comment]
Looks like someone can close this issue due to 347c95e.

**Comment by es128** [comment]
Thanks @realistschuckle!
