### ISSUE TITLE
SassCompiler.prototype.getDependencies throws exception

### ISSUE THREAD

**Issue by bvdeenen** [brunch/sass-brunch#78]
I posted this on [stackoverflow](http://stackoverflow.com/questions/29848917/dont-understand-javascript-bind). The issue is that a sass file with multiple dependencies triggers an exception: `new TypeError('Arguments to path.join must be strings');` According to the responses at stackoverflow, this has to do with the fact that `sys.path.join` is a variadic function, and it doesn't play nice with `bind`.

I solved it by making a diadic function myjoin

    90:    var myjoin = function(a,b){ return sysPath.join(a,b); }
and

    105:   }).map(myjoin.bind(null, parent));
in file `lib/index.js`

I'm not submitting a pull request, because I don't know enough about javascript to even claim that this is the best solution.
But it works :-)

**Comment by es128** [comment]
I'm not sure where the code you're describing is. Perhaps you're using a very old version.

There's no `.map()` with a bound `sysPath.join()` here nor in [progeny](https://github.com/es128/progeny), which is used to generate the `getDependencies` method.
