### ISSUE TITLE
Can't compile bootstrap-sass since version 1.8.7

### ISSUE THREAD

**Issue by wiltzius** [brunch/sass-brunch#79]
Pulling in bootstrap-sass via bower hangs brunch's `build` command from sass-brunch version 1.8.7 onwards.

For an example, see this relatively popular skeleton: https://github.com/ocombe/angular-brunch-seed-no-fuss

As-is, checking it out and running `brunch build --debug` hangs, right after this line:

```
  brunch:pipeline getDependencies 'app/styles/app.scss' with 'SassCompiler' +306ms
```

but fiddling around with various files suggests that the final line isn't the one causing the issue, since I can get it to stop at slightly different points by e.g. commenting out some files.

Significantly, downgrading sass-brunch to 1.8.6 causes the issue to evaporate.

I've reproduced this with an even more minimal repo than the skeleton above, which only uses javascript-brunch and sass-brunch and only has a single bower dependency of bootstrap-sass -- if that would be helpful I can post the repro somewhere.

Very bizarrely, `brunch w` _does_ complete but `brunch b` (with or without --production) does not. No idea what to make of that.

This is affecting my much larger application too, which I'm trying to port from gulp. So far 500 lines of gulp file have turned into 50 lines of brunch-config, so I'm very happy! Just need to iron out the last few issues; this is the worst one remaining. Let me know how I can help solve it! Thanks,

**Comment by es128** [comment]
@wiltzius did you ever figure this out or put together the example repo so someone could help you debug?

**Comment by wiltzius** [comment]
It looks like it's been resolved in more recent versions! I just updated to 1.8.11 and it works with no issues on both `brunch b` and `brunch w` on our bootstrap-sass-based repository. Thanks for following up.
