### ISSUE TITLE
Does not work for across a mac machine with a ubuntu vm

### ISSUE THREAD

**Issue by nicolls1** [brunch/sass-brunch#80]
I use a vagrant VM for running Ubuntu on my Mac. The code is in a shared folder across both. If I install sass-brunch with 'npm install sass-brunch' on the VM everything compiles and runs fine in the VM yet no style sheets are generated. If I do it on Mac no style sheet is generated. I then uninstalled it with 'npm uninstall sass-brunch' and then reinstalled it on Mac with the same install command. This time it worked on Mac and nothing was generated on Ubuntu.

I'm not sure if there is any work around for this or if it is just not possible. I have sass installed on both with sudo gem install sass and I believe it is version 3.4.14.

Thanks

**Comment by nicolls1** [comment]
Detailed log when it does not work:

  brunch:watch Loaded plugins: auto-reload-brunch, javascript-brunch, react-brunch +0ms
  brunch:watch File 'src' received event 'addDir' +6ms
  brunch:watch File 'package.json' received event 'add' +100ms
  brunch:watch File 'brunch-config.coffee' received event 'add' +1ms
  brunch:file-list Reading 'src/actionbar.jsx' +18ms
  brunch:watch File 'src/actionbar.jsx' received event 'add' +1ms
  brunch:file-list Reading 'src/actionbar.scss' +0ms
  brunch:watch File 'src/actionbar.scss' received event 'add' +1ms
  brunch:file-list Reading 'src/audiobar.jsx' +0ms
  brunch:watch File 'src/audiobar.jsx' received event 'add' +0ms
  brunch:file-list Reading 'src/audiobar.scss' +0ms
  brunch:watch File 'src/audiobar.scss' received event 'add' +0ms
  brunch:file-list Reading 'src/participant.scss' +1ms
  brunch:watch File 'src/participant.scss' received event 'add' +0ms
  brunch:file-list Reading 'src/participantlist.jsx' +0ms
  brunch:watch File 'src/participantlist.jsx' received event 'add' +0ms
  brunch:file-list Reading 'src/searchlist.jsx' +1ms
  brunch:watch File 'src/searchlist.jsx' received event 'add' +0ms
  brunch:source-file Initializing fs_utils.SourceFile: {"path":"src/actionbar.jsx","isntModule":false,"isWrapped":true} +57ms
  brunch:source-file Initializing fs_utils.SourceFile: {"path":"src/audiobar.jsx","isntModule":false,"isWrapped":true} +2ms
  brunch:pipeline Compiling 'src/actionbar.jsx' with 'ReactCompiler' +1ms
  brunch:helpers Wrapping '"src/actionbar"' with commonjs +29ms
  brunch:file-list Compiled file 'src/actionbar.jsx'... +2ms
  brunch:source-file Initializing fs_utils.SourceFile: {"path":"src/searchlist.jsx","isntModule":false,"isWrapped":true} +1ms
  brunch:pipeline Compiling 'src/audiobar.jsx' with 'ReactCompiler' +0ms
  brunch:helpers Wrapping '"src/audiobar"' with commonjs +79ms
  brunch:file-list Compiled file 'src/audiobar.jsx'... +2ms
  brunch:pipeline Compiling 'src/searchlist.jsx' with 'ReactCompiler' +0ms
  brunch:helpers Wrapping '"src/searchlist"' with commonjs +26ms
  brunch:file-list Compiled file 'src/searchlist.jsx'... +0ms
  brunch:source-file Initializing fs_utils.SourceFile: {"path":"src/participantlist.jsx","isntModule":false,"isWrapped":true} +1ms
  brunch:pipeline Compiling 'src/participantlist.jsx' with 'ReactCompiler' +0ms
  brunch:helpers Wrapping '"src/participantlist"' with commonjs +20ms
  brunch:file-list Compiled file 'src/participantlist.jsx'... +0ms
  brunch:write Writing 1/1 files +67ms
  brunch:generate Concatenating src/actionbar.jsx, src/audiobar.jsx, src/participantlist.jsx, src/searchlist.jsx to public/javascripts/app.js +4ms
  brunch:common Writing file 'public/javascripts/app.js' +14ms
  brunch:common Writing file 'public/javascripts/app.js.map' +15ms
11 Jun 14:53:00 - info: compiled 4 files into app.js in 3319ms

Detailed log when it does work:
  brunch:watch Loaded plugins: auto-reload-brunch, javascript-brunch, react-brunch, sass-brunch +0ms
  brunch:watch File 'src' received event 'addDir' +5ms
  brunch:watch File 'package.json' received event 'add' +105ms
  brunch:watch File 'brunch-config.coffee' received event 'add' +1ms
  brunch:file-list Reading 'src/actionbar.jsx' +30ms
  brunch:watch File 'src/actionbar.jsx' received event 'add' +1ms
  brunch:file-list Reading 'src/actionbar.scss' +0ms
  brunch:watch File 'src/actionbar.scss' received event 'add' +0ms
  brunch:file-list Reading 'src/audiobar.jsx' +1ms
  brunch:watch File 'src/audiobar.jsx' received event 'add' +0ms
  brunch:file-list Reading 'src/audiobar.scss' +0ms
  brunch:watch File 'src/audiobar.scss' received event 'add' +0ms
  brunch:file-list Reading 'src/participant.scss' +0ms
  brunch:watch File 'src/participant.scss' received event 'add' +0ms
  brunch:file-list Reading 'src/participantlist.jsx' +1ms
  brunch:watch File 'src/participantlist.jsx' received event 'add' +0ms
  brunch:file-list Reading 'src/searchlist.jsx' +0ms
  brunch:watch File 'src/searchlist.jsx' received event 'add' +0ms
  brunch:source-file Initializing fs_utils.SourceFile: {"path":"src/actionbar.jsx","isntModule":false,"isWrapped":true} +65ms
  brunch:source-file Initializing fs_utils.SourceFile: {"path":"src/actionbar.scss","isntModule":false,"isWrapped":false} +2ms
  brunch:source-file Initializing fs_utils.SourceFile: {"path":"src/participant.scss","isntModule":false,"isWrapped":false} +1ms
  brunch:source-file Initializing fs_utils.SourceFile: {"path":"src/participantlist.jsx","isntModule":false,"isWrapped":true} +0ms
  brunch:pipeline Compiling 'src/actionbar.jsx' with 'ReactCompiler' +1ms
  brunch:helpers Wrapping '"src/actionbar"' with commonjs +37ms
  brunch:file-list Compiled file 'src/actionbar.jsx'... +2ms
  brunch:source-file Initializing fs_utils.SourceFile: {"path":"src/searchlist.jsx","isntModule":false,"isWrapped":true} +1ms
  brunch:source-file Initializing fs_utils.SourceFile: {"path":"src/audiobar.jsx","isntModule":false,"isWrapped":true} +0ms
  brunch:pipeline Compiling 'src/actionbar.scss' with 'SassCompiler' +0ms
  brunch:pipeline Compiling 'src/participant.scss' with 'SassCompiler' +29ms
  brunch:source-file Initializing fs_utils.SourceFile: {"path":"src/audiobar.scss","isntModule":false,"isWrapped":false} +1ms
  brunch:pipeline Compiling 'src/participantlist.jsx' with 'ReactCompiler' +0ms
  brunch:helpers Wrapping '"src/participantlist"' with commonjs +16ms
  brunch:file-list Compiled file 'src/participantlist.jsx'... +0ms
  brunch:pipeline getDependencies 'src/actionbar.scss' with 'SassCompiler' +1ms
  brunch:file-list Compiled file 'src/actionbar.scss'... +1ms
  brunch:pipeline getDependencies 'src/participant.scss' with 'SassCompiler' +0ms
  brunch:file-list Compiled file 'src/participant.scss'... +0ms
  brunch:pipeline Compiling 'src/searchlist.jsx' with 'ReactCompiler' +0ms
  brunch:helpers Wrapping '"src/searchlist"' with commonjs +30ms
  brunch:file-list Compiled file 'src/searchlist.jsx'... +1ms
  brunch:pipeline Compiling 'src/audiobar.jsx' with 'ReactCompiler' +0ms
  brunch:helpers Wrapping '"src/audiobar"' with commonjs +71ms
  brunch:file-list Compiled file 'src/audiobar.jsx'... +1ms
  brunch:pipeline Compiling 'src/audiobar.scss' with 'SassCompiler' +1ms
  brunch:pipeline getDependencies 'src/audiobar.scss' with 'SassCompiler' +5ms
  brunch:file-list Compiled file 'src/audiobar.scss'... +0ms
  brunch:write Writing 2/2 files +69ms
  brunch:generate Concatenating src/actionbar.jsx, src/audiobar.jsx, src/participantlist.jsx, src/searchlist.jsx to public/javascripts/app.js +2ms
  brunch:generate Concatenating src/actionbar.scss, src/audiobar.scss, src/participant.scss to public/stylesheets/app.css +13ms
  brunch:common Writing file 'public/javascripts/app.js' +4ms
  brunch:common Writing file 'public/stylesheets/app.css' +1ms
  brunch:common Writing file 'public/stylesheets/app.css.map' +12ms
  brunch:common Writing file 'public/javascripts/app.js.map' +3ms
11 Jun 14:55:16 - info: compiled 7 files into 2 files in 5136ms

**Comment by nicolls1** [comment]
I am only compiling .jsx files and .scss files so you can see no stylesheets are generated when it does not work

**Comment by realistschuckle** [comment]
@nicolls1 If you're using this without specifying the `ruby-sass` binding, what happens is the `npm install` creates bindings for `libsass` for the specific OS/architecture that you're on. So, when you `npm install` on Ubuntu, it creates bindings for GNU/Linux and when you `npm install` it on OS X, you get bindings for Darwin.

So, if you want cross-browser support, specifically say that you want to use the `ruby` version and make sure you have that installed on both your Mac and VM.

```coffeescript
config =
  plugins:
    sass:
      mode: 'ruby'
```
