### ISSUE TITLE
how to disable css concatenation ?

### ISSUE THREAD

**Issue by stoufdev** [brunch/sass-brunch#81]
I have a lot of Scss files, i want to keep then separated.
I just want to compile then in Css (with : sass-brunch), 
and minify (with : i don't know yet, suggestions ?).
How to ? possible ?

**Comment by es128** [comment]
In your brunch config make a separate `joinTo` entry for each file you want the be compiled separately. There is no way in brunch to just disable concatenation across the board.

**Comment by stoufdev** [comment]
ok ! i have problem with syntax with join to...
scss are in the 'styles' folder, exemple files :  accueil.scss, asso.scss,...
and i want all css in public/styles
can you give me the rigth syntax please ?

**Comment by es128** [comment]
```coffee
joinTo:
    'styles/accueil.css': 'styles/accueil.scss'
    'styles/asso.css': 'styles/asso.scss'
```

**Comment by stoufdev** [comment]
do not work, return error

module.exports = config:
  files:
    javascripts: joinTo: 'app.js'
    stylesheets: joinTo:
    'styles/accueil.css': 'styles/accueil.scss'
    'styles/asso.css': 'styles/asso.scss'

syntax error ?

**Comment by es128** [comment]
if you're using coffeescript format you need to use proper indentation

**Comment by stoufdev** [comment]
don't know coffeescript, i need help

**Comment by stoufdev** [comment]
with new indentation, it seem better wirh a new error

warn: 'app/styles/style.scss' compiled, but not written. Check your stylesheets.joinTo config.

module.exports = config:
  files:
    javascripts: joinTo: 'app.js'
    stylesheets: joinTo: 
        'styles/accueil.css': 'styles/accueil.scss'
        'styles/agenda.css': 'styles/agenda.scss'
        'styles/asso.css': 'styles/asso.scss'

**Comment by es128** [comment]
It's not an error, it's a warning. You didn't join style.scss to anything. You could add `'styles/style.css': 'styles/style.scss'` to ensure that source file gets written in its compiled css form and eliminate the warning message.

**Comment by stoufdev** [comment]
This is what i have !! the code was not complete sorry...

errors are for both :
26 Jun 23:14:07 - warn: 'app/styles/accueil.scss' compiled, but not written. Check your stylesheets.joinTo config.
26 Jun 23:14:07 - warn: 'app/styles/agenda.scss' compiled, but not written. Check your stylesheets.joinTo config.
26 Jun 23:14:07 - warn: 'app/styles/style.scss' compiled, but not written. Check your stylesheets.joinTo config.

and the code in brunch-config.coffee
module.exports = config:
  files:
    javascripts:
        joinTo:
            'app.js'
    stylesheets:
        joinTo:
            'styles/accueil.css': 'styles/accueil.scss'
            'styles/agenda.css': 'styles/agenda.scss'
            'styles/style.css': 'styles/style.scss'

**Comment by es128** [comment]
The values on the right may need to specify the app directory. `'styles/style.css': 'app/styles/style.scss'`

**Comment by stoufdev** [comment]
Goooood !!!
Thanks ! thanks ! thanks !
