### ISSUE TITLE
keep scss

### ISSUE THREAD

**Issue by stoufdev** [brunch/sass-brunch#82]
how can i have in my public/styles folder css AND scss files  ?

**Comment by paulmillr** [comment]
1. Make a folder like `app/assets/sass`
2. Make a symbolic link from there to app: `ln -s app/assets/sass app/styles`

**Comment by stoufdev** [comment]
i put sccs in this sass(app/assets/sass) folder but in brunch b -P, the styles folder is not create, juste sass with scss.
No css .

**Comment by es128** [comment]
Brunch does not provide a direct way to do this.

You could use an `onCompile` command to just copy everything from your scss folder over to the appropriate place in public every time a change is detected and Brunch does a compilation cycle. The after-brunch plugin provides another way to do the same kind of thing.

**Comment by stoufdev** [comment]
how to do that ? i need code to understand, i'm new with brunch

**Comment by es128** [comment]
https://github.com/Creative-Licence-Digital/after-brunch

As the command use something like `cp -f app/styles/*.scss public/styles`

**Comment by stoufdev** [comment]
great thanks !

**Comment by stoufdev** [comment]
but did not work, no scss pasted

**Comment by stoufdev** [comment]
i think i have problem with dependencies...Command line is ok in terminal, but afterbrunch and imageoptmizer do not work and browser-sync too...
node -v0.12.4 / npm -v2.11.3
ideas ?? how control install ans dependencies, i do npm update and install

**Comment by es128** [comment]
Use `npm install --save`. Or `--save-dev`. Make sure plugins are listed in your package.json

**Comment by stoufdev** [comment]
yes i did it
