### ISSUE TITLE
Bump node-sass version dependency?

### ISSUE THREAD

**Issue by hypoalex** [brunch/sass-brunch#83]
Hi,

Can we bump the version of the node-sass dependency?

The idea is to pull in this commit so things work on SmartOS.

https://gist.github.com/richland/4c6a3d6d2848b5f78bee - The build failure.

https://github.com/sass/libsass/commit/fb43360f1de24044306ccb910a0cddae6f61e136 - The fix.

More generally, what's the issue with using node-sass 3.x?

**Comment by es128** [comment]
How about you try it and send a PR if it works?

I believe the current version range was set before node-sass 3.x existed.

**Comment by realistschuckle** [comment]
Looks like someone can close this issue due to 347c95ee209b97b559fed6296cd9e94aa8cb94ce.
