### ISSUE TITLE
Update node-sass dependency to >v.3.0.0?

### ISSUE THREAD

**Issue by hinell** [brunch/sass-brunch#85]
Hi guys. In accordance with title.

In light of the new releases of the nodejs and iojs builds, does it has plans to support those latests versions or not?
I know there exists some trouble in node-sass module installation relatively to the mentioned versions   (and iojs > v3) so why not? And also worth it to wait compass integration?

**Comment by paulmillr** [comment]
we're waiting for https://github.com/brunch/sass-brunch/pull/84
