### ISSUE TITLE
disable sourceurl

### ISSUE THREAD

**Issue by Bartmax** [brunch/sass-brunch#91]
how can I disable sourceurl when not in production.? Can be disable for specific file?

**Comment by paulmillr** [comment]
Set sourceMaps: false in your brunch config if that's what you mean.

**Comment by Bartmax** [comment]
i have that, source maps aren't created but I have this on my files:

```
/* line 19, ./bower_components/bootstrap/scss/_normalize.scss */
body {
  margin: 0; }
```

not sure what that is.

**Comment by es128** [comment]
You need `sass: debug: false`
