### ISSUE TITLE
Import many sass or scss files in a single import statement.

### ISSUE THREAD

**Issue by raphaellarrinaga** [brunch/sass-brunch#94]
Hello,

Is it possible to include multiple files in a single statement ala [sass-globbing](https://github.com/chriseppstein/sass-globbing)?

Is it the purpose of the `includePaths` option?
But maybe it is brunch and not sass-brunch related.

**Comment by es128** [comment]
As you point out, this comes from an extension, it is not standard sass behavior. You can install the sass-globbing gem and force the plugin to use ruby mode, although that won't help Brunch understand the dependency relationships to trigger compilation when an included file is edited without further changes.

> Is it the purpose of the includePaths option?

No. That defines where to look for individual files from `@import` statements.
