### ISSUE TITLE
Plugin doesn't register itself with Brunch

### ISSUE THREAD

**Issue by WeKyle** [brunch/sass-brunch#98]
Hey guys,

I'm really puzzled by this issue- it appears that the `sass-brunch` plugin isn't being loaded in Brunch in one of my projects, but in another it works perfectly.

I'm on `brunch@2.1.3` with `sass-brunch@1.9.2`. 

Here's the relevant sections of my `package.json`: 
```
  "dependencies": {
    "css-brunch": "^1.7.0",
  },
  "devDependencies": {
    "angularjs-templates-brunch": "^1.0.0",
    "browser-sync-brunch": "0.0.9",
    "brunch": "^2.1.2",
    "javascript-brunch": "^1.8.0",
    "ng-annotate-brunch": "^1.7.2",
    "postcss-brunch": "^0.5.0",
    "sass-brunch": "^1.9.2",
    "traceur-brunch": "github:wekyle/traceur-brunch",
    "uglify-js-brunch": "^1.7.8"
  },
```

and the plugin statement when I run `brunch b -d`:
```
$ brunch b  -d
  brunch:application Trying to load brunch-config +0ms
  brunch:plugins Loaded plugins: css-brunch, angularjs-templates-brunch, browser-sync-brunch, javascript-brunch, postcss-brunch, traceur-brunch +872ms
```

Any insights? I've tried different combinations of recent versions of both Brunch and sass-brunch, to no avail.

As I mentioned, another project we have uses the same packages at the same versions, and it has no issues.

**Comment by WeKyle** [comment]
Closing- I was able to solve this by:
1. removing `sass-brunch` from my `package.json`
2. running `brunch b`
3. deleting my `./node_modules` folder
4. doing a clean `npm i`
5. running `npm i --save sass-brunch`.


¯\_(ツ)_/¯

**Comment by paulmillr** [comment]
¯_(ツ)_/¯
